### ISSUE TITLE
Fix gh-pages

### ISSUE THREAD

**Issue by hestela** [hestela/rust-psm#16]
ghp-import is handy but for some reason `cargo doc` doesn't create a working website out of the box...
I'm assuming github wants some sort of index.html but cargo only gives main.js.

**Comment by hestela** [comment]
Creating a redirect to the rust_psm directory from the top level that `cargo doc --no-deps` generates seems to be good enough.
Ex:  

``` html
<meta http-equiv="refresh" content="0; url=https://hestela.github.io/rust-psm/rust_psm" />
```

**Comment by acmcarther** [comment]
Heads up btw. If this is on crates io (doesn't look like it yet), [docs.rs](https://docs.rs) will automatically host the documentation for it. Saves effort for gh-pages, especially if you plan to move to jenkins.

[Heres the cucumber docs](https://docs.rs/cucumber/0.3.0/cucumber/)
[And heres docs for a networking crate i didn't even want people to see ](https://docs.rs/gaffer_udp/0.1.2/gaffer_udp/)

**Comment by hestela** [comment]
hmm, looks handy
