### ISSUE TITLE
Make tests

### ISSUE THREAD

**Issue by hestela** [hestela/rust-psm#2]
Since rust-psm is a lib, I have created hestela/rust-psm-tests@c5fd356f11b847732024749c130a89c528901375.
I realize I could have used the build in test features, but I decided to go with a separate repo that will be a cargo binary project

**Comment by acmcarther** [comment]
This is a bit unconventional, but I could roll with it. Generally you want to keep tests in the same repo in a test directory so that they can be run by CI to see that your changes didn't break anything. You may want to change the travis config so that it runs these tests. Kinda weird.

**Comment by hestela** [comment]
The main reason i did this is because of how this library is supposed to work is, you have to concurrently spawn processes either locally or over ssh. I suppose I could make test crate that is a binary project instead of a lib.

**Comment by acmcarther** [comment]
No yeah, make a separate repo for integration tests I think.

But yeah, you'll also want to have unit tests, and probs keep those in the main repo.
